src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>C_External_Person_Key__c</fullName>
        <description>This field is used to store the Bisnode Person Key on an Account record.</description>
        <externalId>true</externalId>
        <label>External Person Key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Reference__c.object
<CustomObject>
    <description>This object is used to store data from EL1 linked to specific references.</description>
    <fields>
        <fullName>C_External_Person_Key__c</fullName>
        <description>This field is used to maintain the External Unique Key.</description>
        <label>External Person Key</label>
        <type>TextArea</type>
    </fields>
    <label>Account Reference</label>
    <nameField>
        <label>Account Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BatchData__c.object
<CustomObject>
    <description>Object for pre-processing data for batch</description>
    <fields>
        <fullName>ObjectName__c</fullName>
        <description>Name of the Object related to the Object Id</description>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>EmailMessage</fullName>
                </value>
                <value>
                    <fullName>Attachment</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Id__c</fullName>
        <description>Parent Id of related object.

Example Parent Id for Attachement of  Email Messages  is Email Messages</description>
        <label>Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Batch Data</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>C_Account_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the Account Reference linked to a Case record.</description>
        <label>Account Reference</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account_Reference__c.C_Account_Name__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Reference__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>C_Concern__c</fullName>
        <description>This field is used to capture the Concern of the case.</description>
        <label>Concern</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>C_Question__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General Inquiry</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>MS In (Lampiris Stolen)</fullName>
                </value>
                <value>
                    <fullName>MS Out (Lampiris Stealer)</fullName>
                </value>
                <value>
                    <fullName>Transfer documents received</fullName>
                </value>
                <value>
                    <fullName>Explanations</fullName>
                </value>
                <value>
                    <fullName>Classic relocation</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Encryption</fullName>
                </value>
                <value>
                    <fullName>Discount application</fullName>
                </value>
                <value>
                    <fullName>Intermediary bill</fullName>
                </value>
                <value>
                    <fullName>Reduced after regulation</fullName>
                </value>
                <value>
                    <fullName>Increase</fullName>
                </value>
                <value>
                    <fullName>Request for duplicate</fullName>
                </value>
                <value>
                    <fullName>Details</fullName>
                </value>
                <value>
                    <fullName>Balanced account activation</fullName>
                </value>
                <value>
                    <fullName>Deactivated after client request</fullName>
                </value>
                <value>
                    <fullName>Relocations</fullName>
                </value>
                <value>
                    <fullName>GRD index correction request</fullName>
                </value>
                <value>
                    <fullName>Overall explanations</fullName>
                </value>
                <value>
                    <fullName>Regularization (not for relocation)</fullName>
                </value>
                <value>
                    <fullName>Reimbursement explanations</fullName>
                </value>
                <value>
                    <fullName>Connection Cuzo</fullName>
                </value>
                <value>
                    <fullName>Retention - prospected by competitor</fullName>
                </value>
                <value>
                    <fullName>Retention - not prospected by competitor</fullName>
                </value>
                <value>
                    <fullName>Retention - Service</fullName>
                </value>
                <value>
                    <fullName>General Information</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Before provision</fullName>
                </value>
                <value>
                    <fullName>Attestations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_Question__c</fullName>
        <description>This field is used to capture the Question linked to a Case record.</description>
        <label>Question</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>C_Service__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Clients</fullName>
                </value>
                <value>
                    <fullName>Isol</fullName>
                </value>
                <value>
                    <fullName>Looking for information</fullName>
                </value>
                <value>
                    <fullName>Mystery Switch</fullName>
                </value>
                <value>
                    <fullName>Screening B2C</fullName>
                </value>
                <value>
                    <fullName>CàB (Wallonie)</fullName>
                </value>
                <value>
                    <fullName>Payment Plan/ Clearance Plan</fullName>
                </value>
                <value>
                    <fullName>Reminder</fullName>
                </value>
                <value>
                    <fullName>I&apos;m the buyer</fullName>
                </value>
                <value>
                    <fullName>My amendment</fullName>
                </value>
                <value>
                    <fullName>GEEP/GEP/Marketing actions/Partners</fullName>
                </value>
                <value>
                    <fullName>Need explanation about my accounts</fullName>
                </value>
                <value>
                    <fullName>Modifying my consumption</fullName>
                </value>
                <value>
                    <fullName>Didn&apos;t receive my bill</fullName>
                </value>
                <value>
                    <fullName>Modifying my client details</fullName>
                </value>
                <value>
                    <fullName>Domiciliation</fullName>
                </value>
                <value>
                    <fullName>Explanations</fullName>
                </value>
                <value>
                    <fullName>Index</fullName>
                </value>
                <value>
                    <fullName>Need explanations/Contest my regularization (not for relocation)</fullName>
                </value>
                <value>
                    <fullName>Want a regularization</fullName>
                </value>
                <value>
                    <fullName>Connection issue</fullName>
                </value>
                <value>
                    <fullName>Client prospected by another provider</fullName>
                </value>
                <value>
                    <fullName>Client not prospected by another provider</fullName>
                </value>
                <value>
                    <fullName>Client wants to leave for service concerns</fullName>
                </value>
                <value>
                    <fullName>General information</fullName>
                </value>
                <value>
                    <fullName>Wood</fullName>
                </value>
                <value>
                    <fullName>Pellets</fullName>
                </value>
                <value>
                    <fullName>I terminate my contract</fullName>
                </value>
                <value>
                    <fullName>Searching for information</fullName>
                </value>
                <value>
                    <fullName>Social Tarif</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_Service__c</fullName>
        <description>This field is used to capture the Service linked to a Case record.</description>
        <label>Service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Clients</fullName>
                </value>
                <value>
                    <fullName>Isol</fullName>
                </value>
                <value>
                    <fullName>I register/terminate</fullName>
                </value>
                <value>
                    <fullName>I&apos;m defaulted</fullName>
                </value>
                <value>
                    <fullName>I&apos;m moving in / out</fullName>
                </value>
                <value>
                    <fullName>My discount/Promotion</fullName>
                </value>
                <value>
                    <fullName>My down payments</fullName>
                </value>
                <value>
                    <fullName>My contractual/administrative/billing details</fullName>
                </value>
                <value>
                    <fullName>My payments</fullName>
                </value>
                <value>
                    <fullName>My regularization</fullName>
                </value>
                <value>
                    <fullName>My reimbursements</fullName>
                </value>
                <value>
                    <fullName>MyLampiris</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>Warm</fullName>
                </value>
                <value>
                    <fullName>Wood</fullName>
                </value>
                <value>
                    <fullName>SPAM</fullName>
                    <isActive>false</isActive>
                    <label>SPAM</label>
                </value>
                <value>
                    <fullName>TBC</fullName>
                    <isActive>false</isActive>
                    <label>TBC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/BatchDataCollection.cls
/*
    @Author: Juraj Ciljak
    @CreateDate: 21.10.2017
    @LastModify: 
    @Description: Helper calss designe out of scope as data container for batch processes
                  Task: --------
                  // TO DO - Better Comments 
    @Version: 1.0.1
*/
public with sharing class BatchDataCollection {

	 public static String ClassName{
        get{
            return BatchDataCollection.class.getName();
        }
    } 
    
    public Map<String,List<sObject>> ObjectContainer{get;set;}  
    public Map<String,Map<String,sObject>> IdContainer{get;set;}
    public Map<String,String> SOQL_Container{get;set;}
    public List<BatchData__c> BatchData {get;set;}
    public SystemLog SysLog {get;set;}
    public Map<String,Object> MapParam{get;set;}
    
    public BatchDataCollection( SystemLog sysLog, Map<String,Object> mapParam)
    {
        this.ObjectContainer = new Map<String,List<sObject>>();
        this.IdContainer = new Map<String,Map<String,sObject>> ();
        this.SOQL_Container = new Map<String,String>();
        this.SOQL_Container.Put( Attachment.sObjectType.getDescribe().getName(), SOQL_AttachementFromParent());
        this.SOQL_Container.Put( EmailMessage.sObjectType.getDescribe().getName(), SOQL_EmailMessage());
        this.SOQL_Container.Put( Case.sObjectType.getDescribe().getName(), SOQL_Case());
        this.SOQL_Container.Put( ContentVersion.sObjectType.getDescribe().getName(), SOQL_ContetnVersion());
        if( mapParam == null )  mapParam = new Map<String,Object>();
        this.MapParam = mapParam;
        
        if( sysLog == null )  sysLog = new SystemLog(false, false, false,false);
        this.SysLog = sysLog;
    }
    
    public void InitColections( List<BatchData__c> batchData,Map<String,String> soql_Container)
    {
        if( batchData != null ) this.BatchData = batchData;
        if( soql_Container != null ) this.SOQL_Container = soql_Container;
        String objectName;
        Map<String,sObject> mapContainer;
    
        for( BatchData__c bd:  this.BatchData )
        {
            if (!String.isEmpty(bd.Object_Id__c))
            {
                objectName = bd.ObjectName__c;
                if( String.isEmpty(objectName) && !String.isEmpty(bd.Object_Id__c)) 
                {
                    objectName = Id.valueOf(bd.Object_Id__c).getSObjectType().getDescribe().getName();
                }
                mapContainer = IdContainer.get(objectName);
                if( mapContainer == null ) mapContainer = new Map<String,sObject>();
                if( objectName == EmailMessage.sObjectType.getDescribe().getName() || 
                	objectName == Case.sObjectType.getDescribe().getName() ||
                	objectName == Attachment.sObjectType.getDescribe().getName() ||
                	objectName == ContentVersion.sObjectType.getDescribe().getName()
                ) 
                	mapContainer.put(bd.Object_Id__c,bd);
                else mapContainer.put(bd.Parent_Id__c,bd);
                IdContainer.put(objectName,mapContainer);
            }       
        }
    }
    
    public List<sObject> getSingleDataColection( String objectType,Set<String> setIds )
    {
        //Set<String> setIds = new Set<String>();       
        String SOQL ;
        DateTime startDate ;
        DateTime endDate;
        Object obj;
        List<sObject> Result = new List<sObject>();
        List<sObject> existData;
        Map<String,sObject> mapIds;
      
        try
        {           
            obj = this.MapParam.get('startDate');
            if( obj != null && (obj instanceof DateTime) )  startDate = DateTime.ValueOf(obj);
            
            obj = this.MapParam.get('endDate');
            if( obj != null && (obj instanceof DateTime) )  endDate = DateTime.ValueOf(obj);
            
            SOQL = this.SOQL_Container.get(objectType);   
            mapIds = IdContainer.get(objectType);
            if( mapIds != null ) setIds.AddAll( mapIds.keySet()); 
            
            system.debug(LoggingLevel.ERROR,'setIds:'+setIds);
            system.debug(LoggingLevel.ERROR,'SOQL:'+SOQL);
            system.debug(LoggingLevel.ERROR,'endDate:'+endDate);
            system.debug(LoggingLevel.ERROR,'startDate:'+startDate);
            
            if( !String.isEmpty(SOQL))  Result = Database.query(SOQL);  
            existData = ObjectContainer.get(objectType);
            if( existData == null ) existData = new List<sObject>();
            existData.AddAll(Result);
            ObjectContainer.put(objectType,existData); 
            return Result;
        }catch(Exception E)
        {        
            sysLog.addLogNoThrow( SystemLog.getSystemLog( BatchDataCollection.ClassName,'start', String.valueOf(e), '?','?',e.getLineNumber(),ApexPages.severity.ERROR ) , e ,true );            
            return new List<sObject>();
        }       
    }
    
    public static String SOQL_AttachementFromParent()
    {
        String Result = ' Select '+SchemaClass.getFields(Attachment.sObjectType.getDescribe().getName(), true) ;
        Result += ' From ' + Attachment.sObjectType.getDescribe().getName();
        Result += ' Where ( Id IN:setIds) ';          
        return Result;
    }
    
    public static String SOQL_ContetnVersion()
    {
        String Result = ' Select '+SchemaClass.getFields(ContentVersion.sObjectType.getDescribe().getName(), true) ;
        Result += ' From ' + ContentVersion.sObjectType.getDescribe().getName();
        Result += ' Where ( Id IN:setIds) ';          
        return Result;
    }
    
    public static String SOQL_EmailMessage()
    {
        String Result = ' Select Parent.Account.C_External_Person_Key__c, ParentId, TextBody, Subject,';  
        Result += ' Parent.C_Service__c, Parent.C_Question__c, Parent.C_Concern__c, Parent.Owner.Name, Parent.OwnerId, Parent.Owner.Alias, ';
        Result += ' Parent.Owner.FirstName, Parent.Owner.LastName, LastModifiedDate, Parent.LastModifiedDate, ';
        Result += ' Parent.Status, Parent.CaseNumber, Parent.Subject, Parent.Description, Parent.C_Account_Reference__r.Name ';       
        Result += ' From  '+EmailMessage.sObjectType.getDescribe().getName()+' Where Id In:setIds  ';
        return Result;
    } 
    
    public static String SOQL_Case()
    { 
        String Result = ' Select Id, Status,CaseNumber, Subject, Description, C_Account_Reference__r.Name,';  
        Result += ' Owner.FirstName, Owner.LastName, LastModifiedDate, ';
        Result += ' C_Service__c, C_Question__c, C_Concern__c,Owner.Name, OwnerId,Owner.Alias ';
     //   Result += ' ( Select  Id, TextBody, Subject From  EmailMessages Where LastModifiedDate >=:startDate AND LastModifiedDate <:endDate )';
        Result += ' From  '+Case.sObjectType.getDescribe().getName()+' Where Id In:setIds  ';
        return Result;
    }
   
}