src/objects/Account_Reference__c.object
<CustomObject>
    <description>This object is used to store data from EL1 linked to specific references.</description>
    <label>Account Reference</label>
    <nameField>
        <label>Account Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BatchData__c.object
<CustomObject>
    <description>Object for pre-processing data for batch</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique Id for upsert</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <description>Name of the Object related to the Object Id</description>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>EmailMessage</fullName>
                </value>
                <value>
                    <fullName>Attachment</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ObjectStatus__c</fullName>
        <label>Object Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Id__c</fullName>
        <description>Parent Id of related object.

Example Parent Id for Attachement of  Email Messages  is Email Messages</description>
        <label>Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>Type of process running in batch</description>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CRM2 Emal Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>T_CaseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Batch Datas</relationshipLabel>
        <relationshipName>BatchDatas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>T_DescriptionHistory__c</fullName>
        <description>Time base Description 
For Example for Case it is Case Number + Case Owner(First Name, Last Name) + Case Status + Case Object + Case Description</description>
        <label>Description History</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>T_ExecutingTime__c</fullName>
        <description>Date time field which trigger time period when this record should be taken in consideration</description>
        <label>Executing Time</label>
        <type>DateTime</type>
    </fields>
    <label>Batch Data</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>C_Account_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the Account Reference linked to a Case record.</description>
        <label>Account Reference</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account_Reference__c.C_Account_Name__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Reference__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>C_Concern__c</fullName>
        <description>This field is used to capture the Concern of the case.</description>
        <label>Concern</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>C_Question__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General Inquiry</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>MS In (Lampiris Stolen)</fullName>
                </value>
                <value>
                    <fullName>MS Out (Lampiris Stealer)</fullName>
                </value>
                <value>
                    <fullName>Transfer documents received</fullName>
                </value>
                <value>
                    <fullName>Explanations</fullName>
                </value>
                <value>
                    <fullName>Classic relocation</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Encryption</fullName>
                </value>
                <value>
                    <fullName>Discount application</fullName>
                </value>
                <value>
                    <fullName>Intermediary bill</fullName>
                </value>
                <value>
                    <fullName>Reduced after regulation</fullName>
                </value>
                <value>
                    <fullName>Increase</fullName>
                </value>
                <value>
                    <fullName>Request for duplicate</fullName>
                </value>
                <value>
                    <fullName>Details</fullName>
                </value>
                <value>
                    <fullName>Balanced account activation</fullName>
                </value>
                <value>
                    <fullName>Deactivated after client request</fullName>
                </value>
                <value>
                    <fullName>Relocations</fullName>
                </value>
                <value>
                    <fullName>GRD index correction request</fullName>
                </value>
                <value>
                    <fullName>Overall explanations</fullName>
                </value>
                <value>
                    <fullName>Regularization (not for relocation)</fullName>
                </value>
                <value>
                    <fullName>Reimbursement explanations</fullName>
                </value>
                <value>
                    <fullName>Connection Cuzo</fullName>
                </value>
                <value>
                    <fullName>Retention - prospected by competitor</fullName>
                </value>
                <value>
                    <fullName>Retention - not prospected by competitor</fullName>
                </value>
                <value>
                    <fullName>Retention - Service</fullName>
                </value>
                <value>
                    <fullName>General Information</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Before provision</fullName>
                </value>
                <value>
                    <fullName>Attestations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_Question__c</fullName>
        <description>This field is used to capture the Question linked to a Case record.</description>
        <label>Question</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>C_Service__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Clients</fullName>
                </value>
                <value>
                    <fullName>Isol</fullName>
                </value>
                <value>
                    <fullName>Looking for information</fullName>
                </value>
                <value>
                    <fullName>Mystery Switch</fullName>
                </value>
                <value>
                    <fullName>Screening B2C</fullName>
                </value>
                <value>
                    <fullName>CàB (Wallonie)</fullName>
                </value>
                <value>
                    <fullName>Payment Plan/ Clearance Plan</fullName>
                </value>
                <value>
                    <fullName>Reminder</fullName>
                </value>
                <value>
                    <fullName>I&apos;m the buyer</fullName>
                </value>
                <value>
                    <fullName>My amendment</fullName>
                </value>
                <value>
                    <fullName>GEEP/GEP/Marketing actions/Partners</fullName>
                </value>
                <value>
                    <fullName>Need explanation about my accounts</fullName>
                </value>
                <value>
                    <fullName>Modifying my consumption</fullName>
                </value>
                <value>
                    <fullName>Didn&apos;t receive my bill</fullName>
                </value>
                <value>
                    <fullName>Modifying my client details</fullName>
                </value>
                <value>
                    <fullName>Domiciliation</fullName>
                </value>
                <value>
                    <fullName>Explanations</fullName>
                </value>
                <value>
                    <fullName>Index</fullName>
                </value>
                <value>
                    <fullName>Need explanations/Contest my regularization (not for relocation)</fullName>
                </value>
                <value>
                    <fullName>Want a regularization</fullName>
                </value>
                <value>
                    <fullName>Connection issue</fullName>
                </value>
                <value>
                    <fullName>Client prospected by another provider</fullName>
                </value>
                <value>
                    <fullName>Client not prospected by another provider</fullName>
                </value>
                <value>
                    <fullName>Client wants to leave for service concerns</fullName>
                </value>
                <value>
                    <fullName>General information</fullName>
                </value>
                <value>
                    <fullName>Wood</fullName>
                </value>
                <value>
                    <fullName>Pellets</fullName>
                </value>
                <value>
                    <fullName>I terminate my contract</fullName>
                </value>
                <value>
                    <fullName>Searching for information</fullName>
                </value>
                <value>
                    <fullName>Social Tarif</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_Service__c</fullName>
        <description>This field is used to capture the Service linked to a Case record.</description>
        <label>Service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Clients</fullName>
                </value>
                <value>
                    <fullName>Isol</fullName>
                </value>
                <value>
                    <fullName>I register/terminate</fullName>
                </value>
                <value>
                    <fullName>I&apos;m defaulted</fullName>
                </value>
                <value>
                    <fullName>I&apos;m moving in / out</fullName>
                </value>
                <value>
                    <fullName>My discount/Promotion</fullName>
                </value>
                <value>
                    <fullName>My down payments</fullName>
                </value>
                <value>
                    <fullName>My contractual/administrative/billing details</fullName>
                </value>
                <value>
                    <fullName>My payments</fullName>
                </value>
                <value>
                    <fullName>My regularization</fullName>
                </value>
                <value>
                    <fullName>My reimbursements</fullName>
                </value>
                <value>
                    <fullName>MyLampiris</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>Warm</fullName>
                </value>
                <value>
                    <fullName>Wood</fullName>
                </value>
                <value>
                    <fullName>SPAM</fullName>
                    <isActive>false</isActive>
                    <label>SPAM</label>
                </value>
                <value>
                    <fullName>TBC</fullName>
                    <isActive>false</isActive>
                    <label>TBC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/CRM2_DataTest.cls
/*
    @Author: Juraj Ciljak
    @CreateDate: 21.10.2017
    @LastModify: 
    @Description: Handler class for Email Message
                  Task: Task: SFBECASE-60  -> https://jira.lampiris.be/browse/SFBECASE-60   
    @Version: 1.0.1
*/
@isTest
private class CRM2_DataTest { 

    @isTest(SeeAllData=true) // SeeAllData beacuse Custom Settings
    static void myCRM2_DataFunctionalTest() {
    	Test.startTest();
    	TST_UtilityClass.TestUtilityWrapperClass utilityTest = new TST_UtilityClass.TestUtilityWrapperClass();
        utilityTest.MainInit(true);
		utilityTest.AccountReferenceInit();
		utilityTest.CaseInit();
		utilityTest.BatchDataInit();
		utilityTest.EmailMessageInit();
		
		utilityTest.testCase = [ Select Id, Owner.Name, OwnerId, CaseNumber,Owner.FirstName, Owner.LastName,
			C_Service__c, C_Question__c, C_Concern__c
		   From Case where Id=:utilityTest.testCase.Id LIMIT 1 ];
		
		
		utilityTest.testBatchData = [ Select T_CaseId__c,T_DescriptionHistory__c,T_ExecutingTime__c,
			External_Id__c, Object_Id__c, ObjectName__c, Parent_Id__c,Process__c,ObjectStatus__c, T_CaseId__r.LastModifiedDate,
			T_CaseId__r.Status, T_CaseId__r.CaseNumber, T_CaseId__r.Subject, T_CaseId__r.Description, LastModifiedDate,
			T_CaseId__r.C_Account_Reference__r.Name, T_CaseId__r.C_Service__c, T_CaseId__r.C_Question__c, T_CaseId__r.C_Concern__c,
			T_CaseId__r.Owner.Name, T_CaseId__r.OwnerId, T_CaseId__r.AccountId, T_CaseId__r.Owner.Alias, T_CaseId__r.Owner.FirstName, 
			T_CaseId__r.Owner.LastName, T_CaseId__r.Account.FirstName, T_CaseId__r.Account.LastName From BatchData__c 
			Where Id=:utilityTest.testBatchData.Id LIMIT 1 ];
		   
		system.debug(LoggingLevel.Error,'utilityTest.testCase:'+utilityTest.testCase );
		String sValue = CRM2_Data.getUserCRM2_Name( utilityTest.testCase.OwnerId, utilityTest.testCase.Owner, '' );
    	
    	system.assertNotEquals(null,sValue);
    	system.assertNotEquals('',sValue);
    	
    	
    	CRM2_Data.CRM2_Email crm2_Email = CRM2_Data.convertSFDCToCRM2_Data( utilityTest.testCase,utilityTest.testBatchData, 
    		CustomSettings.getCRM2_ConcernId(), CustomSettings.getIntegrationCredential( Constants.CS_CRM2_EMAIL_INTEGRATION ) );
	 	
	 	/* Test EmailMessage */
    	utilityTest.testBatchData =  TST_UtilityClass.createTestBatchDataFromEmailMessage( utilityTest.testEmailMessage );
    	Database.upsert( utilityTest.testBatchData,BatchData__c.Fields.External_Id__c);
    	
    	utilityTest.testBatchData = [ Select T_CaseId__c,T_DescriptionHistory__c,T_ExecutingTime__c,LastModifiedDate,
			External_Id__c, Object_Id__c, ObjectName__c, Parent_Id__c,Process__c, ObjectStatus__c,T_CaseId__r.LastModifiedDate,
			T_CaseId__r.Status, T_CaseId__r.CaseNumber, T_CaseId__r.Subject, T_CaseId__r.Description,
			T_CaseId__r.C_Account_Reference__r.Name, T_CaseId__r.C_Service__c, T_CaseId__r.C_Question__c, T_CaseId__r.C_Concern__c,
			T_CaseId__r.Owner.Name, T_CaseId__r.OwnerId, T_CaseId__r.AccountId, T_CaseId__r.Owner.Alias, T_CaseId__r.Owner.FirstName, 
			T_CaseId__r.Owner.LastName, T_CaseId__r.Account.FirstName, T_CaseId__r.Account.LastName From BatchData__c 
			Where Id=:utilityTest.testBatchData.Id LIMIT 1 ];
    	
    	crm2_Email = CRM2_Data.convertSFDCToCRM2_Data( utilityTest.testEmailMessage,utilityTest.testBatchData, 
    		CustomSettings.getCRM2_ConcernId(), CustomSettings.getIntegrationCredential( Constants.CS_CRM2_EMAIL_INTEGRATION ) );
	 	 
	 	/* Testing Attachement */
	 	utilityTest.AttachmentInit();
    	
    	utilityTest.testBatchData =  TST_UtilityClass.createTestBatchDataFromAttachment( utilityTest.testAttachment,
    		utilityTest.testEmailMessage 
		);
    	Database.upsert( utilityTest.testBatchData,BatchData__c.Fields.External_Id__c);
    	
    	utilityTest.testBatchData = [ Select T_CaseId__c,T_DescriptionHistory__c,T_ExecutingTime__c,
			External_Id__c, Object_Id__c, ObjectName__c, Parent_Id__c,Process__c, ObjectStatus__c, T_CaseId__r.LastModifiedDate,
			T_CaseId__r.Status, T_CaseId__r.CaseNumber, T_CaseId__r.Subject, T_CaseId__r.Description,LastModifiedDate,
			T_CaseId__r.C_Account_Reference__r.Name, T_CaseId__r.C_Service__c, T_CaseId__r.C_Question__c, T_CaseId__r.C_Concern__c,
			T_CaseId__r.Owner.Name, T_CaseId__r.OwnerId, T_CaseId__r.AccountId, T_CaseId__r.Owner.Alias, T_CaseId__r.Owner.FirstName, 
			T_CaseId__r.Owner.LastName, T_CaseId__r.Account.FirstName, T_CaseId__r.Account.LastName From BatchData__c 
			Where Id=:utilityTest.testBatchData.Id LIMIT 1 ];
    	
    	crm2_Email = CRM2_Data.convertSFDCToCRM2_Data( utilityTest.testAttachment,utilityTest.testBatchData, 
    		CustomSettings.getCRM2_ConcernId(), CustomSettings.getIntegrationCredential( Constants.CS_CRM2_EMAIL_INTEGRATION ) );
    	
    	
    	CRM2_Data.CRM2_Response resp = new CRM2_Data.CRM2_Response();
    	resp.code = ' some code ';
		resp.message = ' some message';
	  	resp.extraInfo = new List<CRM2_Data.CRM2_Response_ExtraInfo>();
		CRM2_Data.CRM2_Response_ExtraInfo extraInfo = new CRM2_Data.CRM2_Response_ExtraInfo();
		extraInfo.Id = utilityTest.testAttachment.Id;
		resp.extraInfo.Add( extraInfo );
	
    	SystemLog sysLog = new SystemLog(false, false, false, false);
    	String jsonData = JSON.serialize( resp );
    	CRM2_Data.CRM2_Response crm2_Responce = CRM2_Data.deserializeJSON_To_CRM2_Response( jsonData, sysLog);
    	
    	Test.stopTest();
        
    }
}