src/objects/Account_Reference__c.object
<CustomObject>
    <description>This object is used to store data from EL1 linked to specific references.</description>
    <label>Account Reference</label>
    <nameField>
        <label>Account Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BatchData__c.object
<CustomObject>
    <description>Object for pre-processing data for batch</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique Id for upsert</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <description>Name of the Object related to the Object Id</description>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>EmailMessage</fullName>
                </value>
                <value>
                    <fullName>Attachment</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProcessOrder__c</fullName>
        <formula>IF(  
  ISPICKVAL( ObjectName__c , &quot;Case&quot;) &amp;&amp; ObjectStatus__c = &quot;Escalated&quot;,0,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>Type of process running in batch</description>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CRM2 Emal Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>T_CaseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Batch Datas</relationshipLabel>
        <relationshipName>BatchDatas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>T_ExecutingTime__c</fullName>
        <description>Date time field which trigger time period when this record should be taken in consideration</description>
        <label>Executing Time</label>
        <type>DateTime</type>
    </fields>
    <label>Batch Data</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>C_Account_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the Account Reference linked to a Case record.</description>
        <label>Account Reference</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account_Reference__c.C_Account_Name__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Reference__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>C_Concern__c</fullName>
        <description>This field is used to capture the Concern of the case.</description>
        <label>Concern</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>C_Question__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General Inquiry</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>MS In (Lampiris Stolen)</fullName>
                </value>
                <value>
                    <fullName>MS Out (Lampiris Stealer)</fullName>
                </value>
                <value>
                    <fullName>Transfer documents received</fullName>
                </value>
                <value>
                    <fullName>Explanations</fullName>
                </value>
                <value>
                    <fullName>Classic relocation</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Encryption</fullName>
                </value>
                <value>
                    <fullName>Discount application</fullName>
                </value>
                <value>
                    <fullName>Intermediary bill</fullName>
                </value>
                <value>
                    <fullName>Reduced after regulation</fullName>
                </value>
                <value>
                    <fullName>Increase</fullName>
                </value>
                <value>
                    <fullName>Request for duplicate</fullName>
                </value>
                <value>
                    <fullName>Details</fullName>
                </value>
                <value>
                    <fullName>Balanced account activation</fullName>
                </value>
                <value>
                    <fullName>Deactivated after client request</fullName>
                </value>
                <value>
                    <fullName>Relocations</fullName>
                </value>
                <value>
                    <fullName>GRD index correction request</fullName>
                </value>
                <value>
                    <fullName>Overall explanations</fullName>
                </value>
                <value>
                    <fullName>Regularization (not for relocation)</fullName>
                </value>
                <value>
                    <fullName>Reimbursement explanations</fullName>
                </value>
                <value>
                    <fullName>Connection Cuzo</fullName>
                </value>
                <value>
                    <fullName>Retention - prospected by competitor</fullName>
                </value>
                <value>
                    <fullName>Retention - not prospected by competitor</fullName>
                </value>
                <value>
                    <fullName>Retention - Service</fullName>
                </value>
                <value>
                    <fullName>General Information</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Before provision</fullName>
                </value>
                <value>
                    <fullName>Attestations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_Question__c</fullName>
        <description>This field is used to capture the Question linked to a Case record.</description>
        <label>Question</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>C_Service__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Clients</fullName>
                </value>
                <value>
                    <fullName>Isol</fullName>
                </value>
                <value>
                    <fullName>Looking for information</fullName>
                </value>
                <value>
                    <fullName>Mystery Switch</fullName>
                </value>
                <value>
                    <fullName>Screening B2C</fullName>
                </value>
                <value>
                    <fullName>CàB (Wallonie)</fullName>
                </value>
                <value>
                    <fullName>Payment Plan/ Clearance Plan</fullName>
                </value>
                <value>
                    <fullName>Reminder</fullName>
                </value>
                <value>
                    <fullName>I&apos;m the buyer</fullName>
                </value>
                <value>
                    <fullName>My amendment</fullName>
                </value>
                <value>
                    <fullName>GEEP/GEP/Marketing actions/Partners</fullName>
                </value>
                <value>
                    <fullName>Need explanation about my accounts</fullName>
                </value>
                <value>
                    <fullName>Modifying my consumption</fullName>
                </value>
                <value>
                    <fullName>Didn&apos;t receive my bill</fullName>
                </value>
                <value>
                    <fullName>Modifying my client details</fullName>
                </value>
                <value>
                    <fullName>Domiciliation</fullName>
                </value>
                <value>
                    <fullName>Explanations</fullName>
                </value>
                <value>
                    <fullName>Index</fullName>
                </value>
                <value>
                    <fullName>Need explanations/Contest my regularization (not for relocation)</fullName>
                </value>
                <value>
                    <fullName>Want a regularization</fullName>
                </value>
                <value>
                    <fullName>Connection issue</fullName>
                </value>
                <value>
                    <fullName>Client prospected by another provider</fullName>
                </value>
                <value>
                    <fullName>Client not prospected by another provider</fullName>
                </value>
                <value>
                    <fullName>Client wants to leave for service concerns</fullName>
                </value>
                <value>
                    <fullName>General information</fullName>
                </value>
                <value>
                    <fullName>Wood</fullName>
                </value>
                <value>
                    <fullName>Pellets</fullName>
                </value>
                <value>
                    <fullName>I terminate my contract</fullName>
                </value>
                <value>
                    <fullName>Searching for information</fullName>
                </value>
                <value>
                    <fullName>Social Tarif</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_Service__c</fullName>
        <description>This field is used to capture the Service linked to a Case record.</description>
        <label>Service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Clients</fullName>
                </value>
                <value>
                    <fullName>Isol</fullName>
                </value>
                <value>
                    <fullName>I register/terminate</fullName>
                </value>
                <value>
                    <fullName>I&apos;m defaulted</fullName>
                </value>
                <value>
                    <fullName>I&apos;m moving in / out</fullName>
                </value>
                <value>
                    <fullName>My discount/Promotion</fullName>
                </value>
                <value>
                    <fullName>My down payments</fullName>
                </value>
                <value>
                    <fullName>My contractual/administrative/billing details</fullName>
                </value>
                <value>
                    <fullName>My payments</fullName>
                </value>
                <value>
                    <fullName>My regularization</fullName>
                </value>
                <value>
                    <fullName>My reimbursements</fullName>
                </value>
                <value>
                    <fullName>MyLampiris</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>Warm</fullName>
                </value>
                <value>
                    <fullName>Wood</fullName>
                </value>
                <value>
                    <fullName>SPAM</fullName>
                    <isActive>false</isActive>
                    <label>SPAM</label>
                </value>
                <value>
                    <fullName>TBC</fullName>
                    <isActive>false</isActive>
                    <label>TBC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Integration_Credential__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings for store 3d part credential</description>
    <label>Integration Credential</label>
</CustomObject>

src/classes/BAT_CRM2_Integration.cls
/*
    @Author: Juraj Ciljak
    @CreateDate: 13.10.2017
    @LastModify: 
    		27.12.2017 - Juraj - SFBECASE-113
    @Description: Webservice for retrieving data from EL1
                  Task: SFDCFR-11 -> https: https://jira.lampiris.be/browse/SFDCBE-11
                  		SFBECASE-113 - > https://jira.lampiris.be/browse/SFBECASE-113
    @Version: 1.0.1
*/   
global class BAT_CRM2_Integration implements Database.Batchable<sObject>,Database.Stateful , Database.AllowsCallouts{
    
    public Set<String> ParentIds{get;set;}    
    public String RunningVersion{get;set;}
    private DateTime StartTime{get;set;}
    private DateTime FinishTime{get;set;}
    private Integer NumberOfMinutes{get;set;}
    public  Integration_Credential__c IntegrationCred{get;set;}
    public List<BatchData__c> NextExecution{get;set;}
    public SystemLog sysLog {get;set;} 
    public static String ClassName{ 
        get{
            return BAT_CRM2_Integration.class.getName();
        }
    } 
    
    /* Constructor */   
    public BAT_CRM2_Integration(DateTime startTime,DateTime finishTime, Integer numberOfMinutes,String runVersion)
    {
        
        if( startTime == null ) 
        {    
            startTime = Datetime.newInstance(system.now().year(), system.now().month(), system.now().day(),
                                             system.now().hour(),system.now().minute(),0
            );
        } else 
        {
        	startTime = Datetime.newInstance(startTime.year(), startTime.month(), startTime.day(),
                                             startTime.hour(),startTime.minute(),0
            );    
        }
        
        

        this.NumberOfMinutes = numberOfMinutes;
        if( this.NumberOfMinutes == null ) this.NumberOfMinutes = 20; // Default - 20 minutes from now  
        
        this.StartTime = startTime.addMinutes( (-1) * this.NumberOfMinutes);
        
        if ( finishTime == null ) 
        {
            finishTime = this.StartTime.addMinutes(this.NumberOfMinutes);
        } else
        {
        	finishTime = Datetime.newInstance(finishTime.year(), finishTime.month(), finishTime.day(),
                                             finishTime.hour(),finishTime.minute(),0
            );      
        }
        
        this.FinishTime = finishTime;
        
        this.IntegrationCred = CustomSettings.getIntegrationCredential( Constants.CS_CRM2_EMAIL_INTEGRATION );
        this.NextExecution = new List<BatchData__c>();
         
        if( String.isEmpty(runVersion)) runVersion = SCH_CRM2_Integeration.CRON_SCH_CRM2_INTEGRATION_FIRST_RUN;
        this.RunningVersion = runVersion;
        this.ParentIds = new Set<String>();
        
        
        this.sysLog = new SystemLog(false, false, false,false);
    }
    
    /* 
        method start responsible for starting batch process
        @BC: class for content of the batch
    */
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        try{
            
            String SOQL;   
            DateTime endDate = this.FinishTime; 
            DateTime startDate = this.StartTime;
            SOQL = getSOQL_ForBATCH();
            
            system.debug(LoggingLevel.ERROR,'RunningVersion:'+this.RunningVersion);
            system.debug(LoggingLevel.ERROR,'startDate:'+startDate);
            system.debug(LoggingLevel.ERROR,'endDate:'+endDate);
            system.debug(LoggingLevel.ERROR,'SOQL:'+SOQL);
            return Database.getQueryLocator(SOQL);
       }catch(Exception E)
       {        
           sysLog.addLogNoThrow( SystemLog.getSystemLog( BAT_CRM2_Integration.ClassName,'start', String.valueOf(e), '?','?',e.getLineNumber(),ApexPages.severity.ERROR ) , e ,true );            
           return Database.getQueryLocator(' Select Id From ' + BatchData__c.sObjectType.getDescribe().getName() +' Limit 0 '); /* Could not return null !!!!!!! */
       }       
    }
     
     /* 
        method execute responsible for executing the batch and call the WebService in Handler class
        @BC: class for content of the batch
        @scope: Collection of data for processing
    */
    global void execute(Database.BatchableContext BC, List<BatchData__c> scope)
    {
        String objectType;
        Map<String,sObject> mapScope; 
        Set<String> setIds = new Set<String>(); 
        List<sObject> lsData ; 
        Map<String,Object> mapParam ;
        try{
            BAT_HNDL_CRM2_Integration hndl_CRM2 = new BAT_HNDL_CRM2_Integration();
            hndl_CRM2.setAttributes( CustomSettings.getCRM2_ConcernId(), this.IntegrationCred, this.NextExecution, scope , this.sysLog);
            
            mapParam = getQueryParameters();
             
            BatchDataCollection batchDC;
            batchDC = new BatchDataCollection( this.sysLog, mapParam );
            objectType = EmailMessage.sObjectType.getDescribe().getName();
            
            for( BatchData__c bd: scope)
            {
                if( !String.isEmpty(bd.Object_Id__c)) this.ParentIds.Add(bd.Object_Id__c);
            }
             
            batchDC.InitColections( scope ,batchDC.SOQL_Container); 
            mapScope = batchDC.IdContainer.get(objectType);
        
            if( mapScope == null )  mapScope = new Map<String,sObject>();
            setIds.AddAll(mapScope.keySet()); 
             
            hndl_CRM2.MapScopeData = batchDC.IdContainer;
                
            // EmailMessage 
            lsData = batchDC.getSingleDataColection( objectType, setIds); 
          
            //	Cases
            setIds.Clear();
            objectType = Case.sObjectType.getDescribe().getName();
            mapScope = batchDC.IdContainer.get(objectType);
            if( mapScope == null )  mapScope = new Map<String,sObject>();
            setIds.AddAll(mapScope.keySet()); 
            lsData = batchDC.getSingleDataColection( objectType, setIds); 
        
            hndl_CRM2.setBasicAttributes( false,true,false, batchDC.ObjectContainer, this.sysLog);                    
            
            // Handler class for calling WebService
            BatchManager.createHandler(
                BAT_HNDL_CRM2_Integration.class,hndl_CRM2);                               
        
           
        }catch(Exception E)
        {
            sysLog.addLogNoThrow( SystemLog.getSystemLog( BAT_CRM2_Integration.ClassName,'execute', String.valueOf(e), '?','?',e.getLineNumber(),ApexPages.severity.ERROR ) , e ,false );                       
        }
    }
    
    /* 
        method finish is executing after the batch is finish
        @BC: class for content of the batch
    */
    global void finish(Database.BatchableContext BC)
    {
          
        if( sysLog == null ) sysLog = new SystemLog(false, false, false,false);
        Set<String> AttIntIds = new Set<String>();
        Boolean contains;
        try{
            ID jobId = BC.getJobId();
            
            if( this.NextExecution != null && this.NextExecution.size() > 0 )
            {
                // If there is some failure data will run in next batch 
                Database.upsert(this.NextExecution, BatchData__c.Fields.External_Id__c);
                
                for( BatchData__c bd : this.NextExecution )
                {   
                    contains = false;
                    contains = this.ParentIds.contains( bd.Object_Id__c );
                    if( contains = false)  AttIntIds.Add( bd.Object_Id__c );
                    
                }
            } else AttIntIds.AddAll( this.ParentIds );
            
            this.sysLog.checkInsertLog();
                      
            Id batchId = database.executeBatch(new BAT_CRM2_Attachment_Integration(AttIntIds,true),1);
             
             
            
        }catch(Exception E)
        {
            sysLog.addLogNoThrow( SystemLog.getSystemLog( BAT_CRM2_Integration.ClassName,'finish', String.valueOf(e), '?','?',e.getLineNumber(),ApexPages.severity.ERROR ) , e ,true );                     
        }
    } 
    
   public Map<String,Object> getQueryParameters()
    {
    	Map<String,Object> Result = new Map<String,Object>();
    	try{
    		Result.Put('startDate',this.StartTime);
    		Result.Put('endDate',this.FinishTime);
    		return Result;
    	}catch( Exception E )	
    	{
    		sysLog.addLogNoThrow( SystemLog.getSystemLog( BAT_CRM2_Integration.ClassName,'getQueryParameters', String.valueOf(e), '?','?',e.getLineNumber(),ApexPages.severity.ERROR ) , e ,false );                     
        	return new Map<String,Object>();
    	}
    }
    
    public static String getSOQL_ForBATCH()
    {
        String Result = ' Select '+SchemaClass.getFields(BatchData__c.sObjectType.getDescribe().getName(),true);
        Result += ' , T_CaseId__r.Status,T_CaseId__r.CaseNumber, T_CaseId__r.Subject,T_CaseId__r.Description,T_CaseId__r.C_Account_Reference__r.Name, ';
        Result += ' T_CaseId__r.C_Service__c, T_CaseId__r.C_Question__c, T_CaseId__r.C_Concern__c, T_CaseId__r.LastModifiedDate, ';
        Result += ' T_CaseId__r.Owner.Name, T_CaseId__r.OwnerId, T_CaseId__r.AccountId, T_CaseId__r.Owner.Alias, T_CaseId__r.Owner.FirstName, T_CaseId__r.Owner.LastName, ';
        Result += ' T_CaseId__r.Account.FirstName, T_CaseId__r.Account.LastName ';
        Result += ' From ' + SchemaClass.getObjectName( BatchData__c.sObjectType );//BatchData__c.sObjectType.getDescribe().getName();
        Result += ' Where ( T_CaseId__r.C_Account_Reference__c != null ) AND  ';
        Result += ' ( T_ExecutingTime__c >=:startDate AND T_ExecutingTime__c <:endDate) AND ';
        Result += ' ( Process__c =\'BAT_HNDL_CRM2_Integration\')';
        Result += ' Order By ProcessOrder__c ASC, ObjectName__c ';
        if ( Test.IsRunningTest() ) Result += ' LIMIT 10 ';
        return Result;
    }   
}