src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>C_External_Person_Key__c</fullName>
        <description>This field is used to store the Bisnode Person Key on an Account record.</description>
        <externalId>true</externalId>
        <label>External Person Key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Reference__c.object
<CustomObject>
    <description>This object is used to store data from EL1 linked to specific references.</description>
    <fields>
        <fullName>C_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the Account Name on an Account Reference record.</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account References</relationshipLabel>
        <relationshipName>Account_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>C_ExternalId__c</fullName>
        <description>This field is used to store the External Id of an Account Reference record.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C_External_Person_Key__c</fullName>
        <description>This field is used to maintain the External Unique Key.</description>
        <label>External Person Key</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>C_Reference_Type__c</fullName>
        <description>This field is used to store the Reference Type of an Account Reference record.</description>
        <label>Reference Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>ISOL</fullName>
                </value>
                <value>
                    <fullName>TECH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Reference</label>
    <nameField>
        <label>Account Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BatchData__c.object
<CustomObject>
    <description>Object for pre-processing data for batch</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique Id for upsert</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_CaseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Batch Datas</relationshipLabel>
        <relationshipName>BatchDatas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>T_ExecutingTime__c</fullName>
        <description>Date time field which trigger time period when this record should be taken in consideration</description>
        <label>Executing Time</label>
        <type>DateTime</type>
    </fields>
    <label>Batch Data</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>C_Account_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the Account Reference linked to a Case record.</description>
        <label>Account Reference</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account_Reference__c.C_Account_Name__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Reference__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>C_Concern__c</fullName>
        <description>This field is used to capture the Concern of the case.</description>
        <label>Concern</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>C_Question__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General Inquiry</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>MS In (Lampiris Stolen)</fullName>
                </value>
                <value>
                    <fullName>MS Out (Lampiris Stealer)</fullName>
                </value>
                <value>
                    <fullName>Transfer documents received</fullName>
                </value>
                <value>
                    <fullName>Explanations</fullName>
                </value>
                <value>
                    <fullName>Classic relocation</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Encryption</fullName>
                </value>
                <value>
                    <fullName>Discount application</fullName>
                </value>
                <value>
                    <fullName>Intermediary bill</fullName>
                </value>
                <value>
                    <fullName>Reduced after regulation</fullName>
                </value>
                <value>
                    <fullName>Increase</fullName>
                </value>
                <value>
                    <fullName>Request for duplicate</fullName>
                </value>
                <value>
                    <fullName>Details</fullName>
                </value>
                <value>
                    <fullName>Balanced account activation</fullName>
                </value>
                <value>
                    <fullName>Deactivated after client request</fullName>
                </value>
                <value>
                    <fullName>Relocations</fullName>
                </value>
                <value>
                    <fullName>GRD index correction request</fullName>
                </value>
                <value>
                    <fullName>Overall explanations</fullName>
                </value>
                <value>
                    <fullName>Regularization (not for relocation)</fullName>
                </value>
                <value>
                    <fullName>Reimbursement explanations</fullName>
                </value>
                <value>
                    <fullName>Connection Cuzo</fullName>
                </value>
                <value>
                    <fullName>Retention - prospected by competitor</fullName>
                </value>
                <value>
                    <fullName>Retention - not prospected by competitor</fullName>
                </value>
                <value>
                    <fullName>Retention - Service</fullName>
                </value>
                <value>
                    <fullName>General Information</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Before provision</fullName>
                </value>
                <value>
                    <fullName>Attestations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_Question__c</fullName>
        <description>This field is used to capture the Question linked to a Case record.</description>
        <label>Question</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>C_Service__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Clients</fullName>
                </value>
                <value>
                    <fullName>Isol</fullName>
                </value>
                <value>
                    <fullName>Looking for information</fullName>
                </value>
                <value>
                    <fullName>Mystery Switch</fullName>
                </value>
                <value>
                    <fullName>Screening B2C</fullName>
                </value>
                <value>
                    <fullName>CàB (Wallonie)</fullName>
                </value>
                <value>
                    <fullName>Payment Plan/ Clearance Plan</fullName>
                </value>
                <value>
                    <fullName>Reminder</fullName>
                </value>
                <value>
                    <fullName>I&apos;m the buyer</fullName>
                </value>
                <value>
                    <fullName>My amendment</fullName>
                </value>
                <value>
                    <fullName>GEEP/GEP/Marketing actions/Partners</fullName>
                </value>
                <value>
                    <fullName>Need explanation about my accounts</fullName>
                </value>
                <value>
                    <fullName>Modifying my consumption</fullName>
                </value>
                <value>
                    <fullName>Didn&apos;t receive my bill</fullName>
                </value>
                <value>
                    <fullName>Modifying my client details</fullName>
                </value>
                <value>
                    <fullName>Domiciliation</fullName>
                </value>
                <value>
                    <fullName>Explanations</fullName>
                </value>
                <value>
                    <fullName>Index</fullName>
                </value>
                <value>
                    <fullName>Need explanations/Contest my regularization (not for relocation)</fullName>
                </value>
                <value>
                    <fullName>Want a regularization</fullName>
                </value>
                <value>
                    <fullName>Connection issue</fullName>
                </value>
                <value>
                    <fullName>Client prospected by another provider</fullName>
                </value>
                <value>
                    <fullName>Client not prospected by another provider</fullName>
                </value>
                <value>
                    <fullName>Client wants to leave for service concerns</fullName>
                </value>
                <value>
                    <fullName>General information</fullName>
                </value>
                <value>
                    <fullName>Wood</fullName>
                </value>
                <value>
                    <fullName>Pellets</fullName>
                </value>
                <value>
                    <fullName>I terminate my contract</fullName>
                </value>
                <value>
                    <fullName>Searching for information</fullName>
                </value>
                <value>
                    <fullName>Social Tarif</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_Service__c</fullName>
        <description>This field is used to capture the Service linked to a Case record.</description>
        <label>Service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Clients</fullName>
                </value>
                <value>
                    <fullName>Isol</fullName>
                </value>
                <value>
                    <fullName>I register/terminate</fullName>
                </value>
                <value>
                    <fullName>I&apos;m defaulted</fullName>
                </value>
                <value>
                    <fullName>I&apos;m moving in / out</fullName>
                </value>
                <value>
                    <fullName>My discount/Promotion</fullName>
                </value>
                <value>
                    <fullName>My down payments</fullName>
                </value>
                <value>
                    <fullName>My contractual/administrative/billing details</fullName>
                </value>
                <value>
                    <fullName>My payments</fullName>
                </value>
                <value>
                    <fullName>My regularization</fullName>
                </value>
                <value>
                    <fullName>My reimbursements</fullName>
                </value>
                <value>
                    <fullName>MyLampiris</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>Warm</fullName>
                </value>
                <value>
                    <fullName>Wood</fullName>
                </value>
                <value>
                    <fullName>SPAM</fullName>
                    <isActive>false</isActive>
                    <label>SPAM</label>
                </value>
                <value>
                    <fullName>TBC</fullName>
                    <isActive>false</isActive>
                    <label>TBC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>T_Case_Number__c</fullName>
        <description>This field is used to flag the Case Number as External Id.</description>
        <externalId>true</externalId>
        <label>Case Number (External Id)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/TST_UtilityClass.cls
/*
    @ Author: Juraj Ciljak
    @ Description: Test class stored helper function for generate records in Unit Test
    @ CreatedDate: 24.07.2017
    @ LastModify:
    @ Notes:  
    @ Version: 1.0.1
*/
@isTest
public class TST_UtilityClass {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
    }
    
    
	public static Profile getProfileByName(String profileName) {
	  	Profile Result  = [Select Id from Profile where Name = :profileName];
	  	return Result;
	}
	
	public static User createTestUser(Profile pf) {
		return TST_UtilityClass.createTestUser(pf, 'testuser@test123456789.com');
  	}
  
  	public static User createTestUser(Profile pf, String userName) {
    	Blob blobKey = crypto.generateAesKey(192);
		String key = EncodingUtil.base64encode(blobKey);
    	User Result = new User();
        Result.FirstName = 'Test';
        Result.LastName = 'User';
        Result.Email = 'testuser@test123456789.com'; 
        Result.CompanyName = 'test.com';
        Result.Title = 'Test User';
        Result.Username = key+'_'+userName;
        Result.Alias = 'testuser';
        Result.CommunityNickname = key.substring(25)+'_Test User';
        Result.TimeZoneSidKey = 'Europe/Amsterdam';
        Result.LocaleSidKey = 'nl_NL';
        Result.EmailEncodingKey = 'ISO-8859-1';
        Result.ProfileId = pf.Id;
		Result.LanguageLocaleKey = 'nl_NL';
     	return Result;
  	}
    
    public static Account_Reference__c createTestAccountReference( Account acc )
    {
    	Account_Reference__c Result = new Account_Reference__c(
    		C_Account_Name__c = acc.Id,
    		C_ExternalId__c	= 'EL1234567',
    		C_External_Person_Key__c = 'EL1234567',
    		C_Reference_Type__c = Constants.ACCOUNT_REFERENCE_REFERENCE_TYPE_ENERGY
    	);
    	return Result;
    }
    
    public static Case createTestCase( Account_Reference__c accRef,User usr)
    {
    	Id userId = UserInfo.getUserId();
    	if( usr != null && !String.isEmpty(usr.Id)) userId = usr.Id;
    	Blob blobKey = crypto.generateAesKey(192);
		String key = EncodingUtil.base64encode(blobKey); 
    	Case Result = new Case(
    		AccountId = accRef.C_Account_Name__c,
    		C_Account_Reference__c	= accRef.Id,
    		Status = Constants.CASE_STATUS_WORKING,
	 		Origin = Constants.CASE_ORIGIN_EMAIL,
	 		OwnerId = userId,
	 		C_Service__c = 'Corporate Clients',
			C_Question__c = 'Corporate Clients',
			C_Concern__c = 'General Inquiry',
			T_Case_Number__c = String.valueOf(system.now())+''+key
    	);
    	system.debug(LoggingLevel.Error,'Case:'+Result);
    	return Result;
    }
    
    public static Account createTestAccount(String accName,String phone, Account parentAcc) {
        String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Business Account').getRecordTypeId();       
        Account Result = new Account(
        	RecordTypeID = recordTypeId ,
        	Name = accName,
        	Phone = phone
		);
        if (parentAcc != null) Result.ParentId = parentAcc.Id;
        return Result;
    }
  	
  	
    public static ContentVersion createTestContentVersion( EmailMessage eml )
    {
   		ContentVersion Result = new ContentVersion( 
			title = 'Test title',
			VersionData = blob.valueof('New Bitmap Image.bmp'),
         	//EmailMessageId = eml.id
         	PathOnClient ='/Header_Picture1.jpg'
   
    	 
		);
    	return Result;
    }
    
  	public static BatchData__c createTestBatchDataFromCase( Case cs ){
  		 
  		BatchData__c Result = new BatchData__c(
  			T_CaseId__c = cs.Id,
  			Object_Id__c = cs.Id,
  			External_Id__c = cs.Id,
  			T_ExecutingTime__c = system.now(),
  			ObjectName__c = SchemaClass.getObjectName( Case.SObjectType)
  		
  		);
  		return Result;			
  	}
  	  	
  	public static BatchData__c createTestBatchDataFromEmailMessage( EmailMessage eml ){
  		 
  		BatchData__c Result = new BatchData__c(
  			T_CaseId__c = eml.ParentId,
  			Object_Id__c = eml.Id,
  			External_Id__c = eml.Id,
  			Parent_Id__c = eml.ParentId,
  			T_ExecutingTime__c = system.now(),
  			ObjectName__c = SchemaClass.getObjectName( EmailMessage.SObjectType),
  			Process__c = 'BAT_HNDL_CRM2_Integration'//BAT_HNDL_CRM2_Integration.ClassName 
  		
  		);
  		return Result;			
  	}
  	
  	public static BatchData__c createTestBatchDataFromAttachment( Attachment att, EmailMessage eml )
	{
  		 
  		BatchData__c Result = new BatchData__c(
  			T_CaseId__c = eml.ParentId,
  			Object_Id__c = att.Id,
  			External_Id__c = att.Id,
  			Parent_Id__c = eml.ParentId,
  			T_ExecutingTime__c = system.now(),
  			ObjectName__c = SchemaClass.getObjectName( Attachment.SObjectType)
  		);
  		return Result;			
  	}

  	public static Attachment createTestAttachemnt( Id parentId )
  	{
  		Attachment Result = new Attachment(  	
	    	Name = 'Unit Test Attachment',
	    	body = Blob.valueOf('Unit Test Attachment Body'),
	        parentId = parentId
  		);
        return Result;
  	}
  	
  	
  	
  	public static ContentDocumentLink createTestContentDocumentLink( Id contDocumentId, Id entityId )
  	{
  	 	ContentDocumentLink Result = new ContentDocumentLink(
	        ShareType = 'V',
	        LinkedEntityId = entityId, 
	        ContentDocumentId = contDocumentId,
	        Visibility = 'AllUsers'
  		);
  		return Result;
  	}
  	
  	
	public static Account createTestPersonAccount(String firstName, String lastName, String phone, String email) {  
		String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account Result = new Account(
          RecordTypeID = recordTypeId ,
          FirstName = firstName,
          LastName = lastName,
          PersonEmail = email,
          PersonMailingStreet='test@asUgo.com',
          PersonMailingPostalCode='12345',
          PersonMailingCity='SFO',
          PersonMobilePhone = phone,
          Phone = phone
		  
        ); 
    	return Result;     
	}
	
	public static EmailMessage testEmailMessage( Case cs, String subjectName )
	{
		EmailMessage Result = new EmailMessage(
			ParentId = cs.Id,
			Subject = subjectName,
			FromAddress = UserInfo.getUserEmail()
		);
		
		return Result;
	}
	

	
 /*   public static Contact createTestContact(String contactName, Account acco)
    {
    	Contact Result = new Contact();
        Result.LastName = contactName;
        Result.Email = 'myEmail@asUgo.com';
        Result.AccountId = acco.Id;
        
        return Result;
        
    }
    */
   /* public static Lead createTestLead(String firstName, String lastName, String email,String mobile)
    {
    	Lead Result = new Lead(
        	LastName = lastName,
        	FirstName = firstName,
        	Email = email,
        	MobilePhone = mobile,
        	Phone = mobile,
        	PostalCode = '1001'
        );
        return Result;        
    }
    */
    
    public static Map<Id,Account> getAccountsByIds(Set<String> setIds)
    {
    	Map<Id,Account> Result = new Map<Id,Account>([select Id,Name From Account where Id IN:setIds]);
    	
    	return Result;    
    }
    
 
    
    public class TestUtilityWrapperClass{
    	public Account testSupplier {get;set;}
    	public Account_Reference__c testAccountReference{get;set;}
	    public Account testClient   {get;set;}
	    public Account testBilling   {get;set;}
	    public Account testEndCustomer {get;set;}
	    public Account testPersonAccount {get;set;}
	    public Contact testContact{get;set;}
    	public List<Account> lsAccount {get;set;}
    	public Profile testProfil{get;set;}
    	public User testUser{get;set;}
    	public Lead testLead{get;set;}
    	public Case testCase{get;set;}
    	public BatchData__c testBatchData{get;set;}
    	public EmailMessage testEmailMessage{get;set;}
    	public Attachment testAttachment{get;set;}
    	public ContentVersion testContentVersion{get;set;}
    	public ContentDocumentLink testContentDocumentLink{get;set;}
	  //  public Campaign testCampaign{get;set;}
	  //  public CampaignMember testCampignMember{get;set;}
	    
	       
    	public TestUtilityWrapperClass()
    	{
    		this.lsAccount = new List<Account>();
    	}
    	
    	public void updateAccount(Map<Id,Account> mapData)
    	{
    		List<Account> Result = new List<Account>();
    		Account Acc ;
    		if( mapData != null & mapData.size() > 0)
    		{
    			for(Id sKey:  mapData.keySet())
	   	 		{
	   	 			Acc = mapData.get(sKey);
	   	 			
	   	 			Result.Add(acc);
	   	 		}
	   	 		update Result;
    		}	
    	}
    	
    	
    	
    	public void UserInit()
    	{
    		this.testProfil = TST_UtilityClass.getProfileByName('System Administrator');  	
    		this.testUser = TST_UtilityClass.createTestUser(this.testProfil);
	    	insert this.testUser;
    	}
    	
    	public void MainInit(Boolean initUser)
    	{ 
    		lsAccount.Clear();
    		if( initUser == true ) UserInit();
	    	
	    	
	        this.testSupplier = TST_UtilityClass.createTestAccount('Account 1','0474123456',null); 
	    	this.testClient   = TST_UtilityClass.createTestAccount('Account 2','0474123457',null);
	    	this.testBilling  = TST_UtilityClass.createTestAccount('Account 3','0474123458',null);
	    	this.testEndCustomer = TST_UtilityClass.createTestAccount('End Customer 1','0474123459',null);
	    	this.testPersonAccount = TST_UtilityClass.createTestPersonAccount('Person Account','1','0474123452','personaccount.1@lampiris.fr');
	    	this.lsAccount.add(this.testEndCustomer);
	    	this.lsAccount.add(this.testSupplier);
	    	this.lsAccount.add(this.testClient);
	    	this.lsAccount.add(this.testBilling);
	    	this.lsAccount.add(this.testPersonAccount);
	    	system.debug(LoggingLevel.Error,'Accounts: '+lsAccount);
	   	 	insert this.lsAccount;	        	
    	}
    	
    	public void AccountReferenceInit()
    	{
    		this.testAccountReference = TST_UtilityClass.createTestAccountReference(this.testPersonAccount);
    		insert this.testAccountReference;
        
    	}
    	
    	public void CaseInit()
    	{
    		this.testCase = TST_UtilityClass.createTestCase( this.testAccountReference, this.testUser );
	    	Database.upsert( this.testCase, Case.Fields.T_Case_Number__c);
        
    	}
    	
    	public void EmailMessageInit()
    	{
    		this.testEmailMessage = TST_UtilityClass.testEmailMessage( this.testCase,' Test Email' );
    		insert this.testEmailMessage;
    	}
    	
    	public void AttachmentInit()
    	{
    		this.testAttachment = TST_UtilityClass.createTestAttachemnt( this.testEmailMessage.Id );
    		insert this.testAttachment;
    	}
    	
    	public void BatchDataInit()
    	{
    		this.testBatchData = createTestBatchDataFromCase( this.testCase );
    		insert this.testBatchData;
    	}
    	
    	public void CRM2_IntegrationCredInit() 
    	{
    		Integration_Credential__c IntegrationCred = new Integration_Credential__c( 
    			Name = Constants.CS_CRM2_EMAIL_INTEGRATION,
    			ApplicationName__c = Constants.CRM2_INTEGRATION_TEST_APPLICATION_NAME,
				ApplicationUser__c = Constants.CRM2_INTEGRATION_TEST_APPLICATION_USER,
				EndPoint__c = Constants.CRM2_INTEGRATION_TEST_ENDPOINT,
				Password__c = Constants.CRM2_INTEGRATION_TEST_PASSWORD,
				UserName__c = Constants.CRM2_INTEGRATION_TEST_USER_NAME
			);  
   			insert IntegrationCred;
    	}

		/* 08.01.2018 - Mohamed */
		public void CPAS_EmailAddressInit()
		{
			CPAS_EmailAddress__c cpasEmailAddress = new CPAS_EmailAddress__c(
					Name = 'tst@tst.com',
					Email_Address__c='tst@tst.com'
			);
			insert cpasEmailAddress;
		}
		
    	
    	public void ContentDocumentInit()
    	{
    		this.testContentVersion = TST_UtilityClass.createTestContentVersion( this.testEmailMessage );			
			insert this.testContentVersion;
			
			
			this.testContentVersion = [SELECT id, title, VersionData, PathOnClient,ContentDocumentId 
				FROM ContentVersion where Id = :this.testContentVersion.Id];
				
			this.testContentDocumentLink = TST_UtilityClass.createTestContentDocumentLink( this.testContentVersion.ContentDocumentId, this.testEmailMessage.Id );
			
        	insert this.testContentDocumentLink;
			
			
    		
    	}
    	
    /*	public void ContactInit()
	    {
	    	this.testContact = TST_UtilityClass.createTestContact(':)', this.testClient);
	        	        
	        insert this.testContact;
	        
	    } */  	
    }
    
    
}