src/objects/BatchData__c.object
<CustomObject>
    <description>Object for pre-processing data for batch</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique Id for upsert</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>T_CaseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Batch Datas</relationshipLabel>
        <relationshipName>BatchDatas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>T_ExecutingTime__c</fullName>
        <description>Date time field which trigger time period when this record should be taken in consideration</description>
        <label>Executing Time</label>
        <type>DateTime</type>
    </fields>
    <label>Batch Data</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>C_Account_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the Account Reference linked to a Case record.</description>
        <label>Account Reference</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account_Reference__c.C_Account_Name__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Reference__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>T_Status_Changed_To_Escalated__c</fullName>
        <description>This field is used to store the date/time upon which the status was changed to &quot;Escalated&quot;</description>
        <label>Status Changed To Escalated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>T_Status_Changed_To_OnHold_Customer__c</fullName>
        <description>This field is used to store the date/time upon which the status was changed to &quot;On Hold - Awaiting Customer&quot;</description>
        <label>Status Changed To On Hold Customer</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>T_Status_Changed_To_OnHold_Support__c</fullName>
        <description>This field is used to store the date/time upon which the status was changed to &quot;On Hold - Awaiting Support&quot;</description>
        <label>Status Changed To On Hold Support</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>T_Status_Changed_To_Re_opened__c</fullName>
        <description>This field is used to store the date/time upon which the status was changed to &quot;Re-opened&quot;</description>
        <label>Status Changed To Re-opened</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>T_Status_Changed_To_Working__c</fullName>
        <description>This field is used to store the date/time upon which the status was changed to &quot;Working&quot;</description>
        <label>Status Changed To Working</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CPAS_EmailAddress__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting containing CPAS email addresses</description>
    <fields>
        <fullName>Email_Address__c</fullName>
        <description>Email Address of CPAS agent</description>
        <label>Email Address</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>CPAS email address</label>
</CustomObject>

src/classes/HLPR_CaseService.cls
/*
	@Author: Juraj Ciljak
	@CreateDate: 04.01.2018
	@LastModify: 
	@Description:  Helper class for Case Hanlder 
			Task: SFBECASE-113 - https://jira.lampiris.be/browse/SFBECASE-113
			Task: SFBECASE-126 - https://jira.lampiris.be/browse/SFBECASE-126
	@Version: 1.0.1
*/

public with sharing class HLPR_CaseService {

    public static String ClassName{
        get{
            return HLPR_CaseService.class.getName();       
        }
    }

    public static void removeAccountlinkToCaseForCpasMail(List <SObject> newList){
		/*
		@newMap: Collection of new changes in case
		 */
		List<Case> caseNewList;
		SystemLog sysLog = new SystemLog(false, false, false, false);
		try {
			caseNewList=newList;
			if (newList != null && newList.size() > 0) {
				for( Case cs: caseNewList ) {
					CPAS_EmailAddress__c cpasEmailAddress = CustomSettings.getCpasEmailAddress(cs.SuppliedEmail);
					if (cpasEmailAddress!=null && !String.isEmpty(cpasEmailAddress.Email_Address__c) ) {//It's a CPAS email, so remove automatic linking of Account to Case
						cs.AccountId=null;
						cs.ContactId=null;
					}

				}
			}
		}catch( Exception E)
			{
			sysLog.addLogNoThrow( SystemLog.getSystemLog( HLPR_CaseService.ClassName,'initAccountCase', String.valueOf(e), '?','?',e.getLineNumber(),ApexPages.severity.ERROR ) , e ,true );
		}
	}



	public static void updateCaseAccountReference(Map<Id,sObject> newMap, Map<Id,sObject> oldMap)  
	{
		/* 
	        method finish is executing after the batch is finish
	        @newMap: Collection of new changes in case
	        @oldMap: Collection of old data in case
    	*/
		
		Case csOld;
		List<BatchData__c> Result;
		Map<Id,Case> caseOldMap;
		Map<Id,Case> caseNewMap;
		Set<Id> caseIds = new Set<Id>();
		
		/* Custom Classes*/
        SystemLog sysLog = new SystemLog(false, false, false, false);
        /* System Objects */
        Database.UpsertResult [] upr ;
		try{
			if( newMap != null && newMap.size() > 0)
			{
				caseNewMap = (Map<Id,Case>)newMap;		
				if( oldMap != null ) caseOldMap = (Map<Id,Case>)oldMap;
				else caseOldMap = caseNewMap;
				
				for( Case cs: caseNewMap.values() )
				{ 
					csOld = caseOldMap.get(cs.Id);
					
					if( csOld == null ) csOld = cs; // nothing changed
					
					if( !String.isEmpty(cs.C_Account_Reference__c) && String.isEmpty(csOld.C_Account_Reference__c) )  
						// Need Id only from cases where Account reference was null
					{
						caseIds.Add(cs.Id);
					}	
				}	//	END for( Case cs: caseNewMap.values() )	
				
				Result = getBatchDataBaseOnAccountReferenceUpdate( caseIds );
				if( Result != null && Result.size() > 0 ) upr = Database.upsert(Result, BatchData__c.Fields.External_Id__c);
        		SystemLog.checkUpsertResult(Case.sObjectType.getDescribe().getName(), upr, Result, sysLog );
            	sysLog.checkInsertLog();
			}
			
		}catch( Exception E)
		{
			sysLog.addLogNoThrow( SystemLog.getSystemLog( HLPR_CaseService.ClassName,'updateCaseAccountReference', String.valueOf(e), '?','?',e.getLineNumber(),ApexPages.severity.ERROR ) , e ,false );		
			sysLog.checkInsertLog();	          
		}
	}  
	
	public static List<BatchData__c> getBatchDataBaseOnAccountReferenceUpdate( Set<Id> caseIds  )
	{
		List<BatchData__c> Result = new List<BatchData__c> ();
		List<BatchData__c> lsData; 
	    SystemLog sysLog = new SystemLog(false, false, false, false);
       
		try
		{
			system.debug(LoggingLevel.Error,'caseIds:'+caseIds);
			if ( caseIds != null && caseIds.size() > 0  )
			{
				lsData = [ Select Id,T_ExecutingTime__c,External_Id__c From BatchData__c 
					Where T_CaseId__c IN:caseIds LIMIT 10000
				]; // Everything what were not pushed before because lack of Account reference on case 
			}
			
			if( lsData != null && lsData.size() >0 )
			{
				for(BatchData__c bd:lsData)
				{
					bd.T_ExecutingTime__c = system.now();
					Result.Add(bd);	
				}
			}
			return Result;	
		}catch(Exception E)
		{			
			sysLog.addLogNoThrow( SystemLog.getSystemLog( HLPR_CaseService.ClassName,'getBatchDataBaseOnAccountReferenceUpdate', String.valueOf(e), '?','?',e.getLineNumber(),ApexPages.severity.ERROR ) , e ,true );			  
        	return null;
		}
	}
	
	public static void checkStatusData( List <SObject> soLst, Map<Id,sObject> oldMap, Map<Id,sObject> newMap )
    {         
    	/* 
	        checkStatusData responsible for populating timestamp based on changing status
	        @soLst:  Collection of casses processed in trigger
	        @newMap: Map Collection of new changes in case
	        @oldMap: Map Collection of old data in case
    	*/   
       
       
        /* sObject Data */
        Case oldCase;
        sObject sObj;
        List<Case> lsCase = new List<Case>();       
        Map<Id,Case> oldCases = new Map<Id,Case>();
        
        /* Custom Classes*/
        SystemLog sysLog = new SystemLog(false, false, false, false);
       
        if( oldMap != null ) oldCases = (Map<Id,Case>)oldMap;
        if( soLst != null ) lsCase = (List<Case>)soLst; 

        try
        {
        	
        	
        	for( Case cs: lsCase){
        		oldCase = oldCases.get(cs.Id);
        		if( oldCase == null ) oldCase = new Case();
        		
        		if( cs.Status != oldCase.Status){
        			if( cs.Status == Constants.CASE_STATUS_WORKING )	
        			{
        				cs.T_Status_Changed_To_Working__c  = system.now();		
        			} else if( cs.Status == Constants.CASE_STATUS_ESCALATED )
        			{
        				cs.T_Status_Changed_To_Escalated__c = system.now();	
        				
        			} else if( cs.Status == Constants.CASE_STATUS_RE_OPENED )
        			{
        				cs.T_Status_Changed_To_Re_opened__c	 = system.now();	 
        			} else if( cs.Status == Constants.CASE_STATUS_ON_HOLD_CUSTOMER )
        			{
        				cs.T_Status_Changed_To_OnHold_Customer__c = system.now();
        					
        			} else if( cs.Status == Constants.CASE_STATUS_ON_HOLD_SUPPORT )
        			{
        				cs.T_Status_Changed_To_OnHold_Support__c = system.now();	
        				
        			}  
        			 	
        		}	// END if( cs.Status != old.Status)
        	}
        	
        	sysLog.checkInsertLog();
        }catch(Exception E)
        {
            sysLog.addLogNoThrow( SystemLog.getSystemLog( HNDL_Case.ClassName,'checkStatusData', String.valueOf(e), '?','?',e.getLineNumber(),ApexPages.severity.ERROR ) , e ,true );			  
        } 
    }
}