src/objects/BatchData__c.object
<CustomObject>
    <description>Object for pre-processing data for batch</description>
    <fields>
        <fullName>T_CaseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Batch Datas</relationshipLabel>
        <relationshipName>BatchDatas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>T_ExecutingTime__c</fullName>
        <description>Date time field which trigger time period when this record should be taken in consideration</description>
        <label>Executing Time</label>
        <type>DateTime</type>
    </fields>
    <label>Batch Data</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>C_Account_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the Account Reference linked to a Case record.</description>
        <label>Account Reference</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account_Reference__c.C_Account_Name__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Reference__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/BAT_BatchData_Clean_Up.cls
/*
    @Author: Juraj Ciljak
    @CreateDate: 25.10.2017
    @LastModify: 
    @Description: Schedule Batch for CRM2 and SFDC integeration
                  Task: SFDCFR-60 -> https: https://jira.lampiris.be/browse/SFDCBE-60
    @Version: 1.0.1
*/
global class BAT_BatchData_Clean_Up implements Database.Batchable<sObject>,Database.Stateful {

	public static String ClassName{
        get{ 
            return BAT_BatchData_Clean_Up.class.getName();
        }
    } 
    
    public SystemLog sysLog {get;set;}
    
    public BAT_BatchData_Clean_Up()
    {   
    	this.sysLog = new SystemLog(false, false, false,false);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        try{
            
            String SOQL;   
            DateTime endDate = system.now().addMonths( ( -1  ) ); 
            SOQL = getSOQL_ForBATCH();
            
            system.debug(LoggingLevel.ERROR,'endDate:'+endDate);
            system.debug(LoggingLevel.ERROR,'SOQL:'+SOQL);
            return Database.getQueryLocator(SOQL);
       }catch(Exception E)
       {        
           sysLog.addLogNoThrow( SystemLog.getSystemLog( BAT_BatchData_Clean_Up.ClassName,'start', String.valueOf(e), '?','?',e.getLineNumber(),ApexPages.severity.ERROR ) , e , false );            
           return Database.getQueryLocator(' Select Id From ' + BatchData__c.sObjectType.getDescribe().getName() +' Limit 0 '); /* Could not return null !!!!!!! */
       }       
    }
     
 
    global void execute(Database.BatchableContext BC, List<BatchData__c> scope)
    {
         try{
        	if( scope != null && scope.size() > 0 ) delete scope;
            this.sysLog.checkInsertLog();
        
        }catch(Exception E)
        {
            sysLog.addLogNoThrow( SystemLog.getSystemLog( BAT_BatchData_Clean_Up.ClassName,'execute', String.valueOf(e), '?','?',e.getLineNumber(),ApexPages.severity.ERROR ) , e ,false );                       
        }
    }
    
    global void finish(Database.BatchableContext BC)
    {
    	if( sysLog != null ) this.sysLog.checkInsertLog();
            
    }
    
    public static String getSOQL_ForBATCH()
    {
        String Result = ' Select Id ';
        Result += ' From ' + SchemaClass.getObjectName( BatchData__c.sObjectType );//BatchData__c.sObjectType.getDescribe().getName();
        Result += ' Where ( T_CaseId__r.C_Account_Reference__c != null )  ';
                
        if ( Test.IsRunningTest() ) Result += ' LIMIT 10 ';
        else Result += ' AND  ( T_ExecutingTime__c <=:endDate)  ';
        
        return Result;
    }   
}